### ISSUE TITLE
Release for Ubuntu

### ISSUE THREAD

**Issue by paulstodghill** [degaart/firefox-user-installer#1]
Thank you very much for putting this package together. Your solution for bringing the release version of Firefox to Debian Stable is ... elegant.

This issue is only a suggestion that you release a .deb of this package for Ubuntu 22.04, which also does not provide a (non-Snap) release version of Firefox. The Debian .deb does not install on 22.04 (libssl version conflict), but I recreated the .deb on one of my 22.04 systems and it works like a champ. I suspect that other Ubuntu users would find it very helpful.

Again, thanks for providing this package.

**Comment by degaart** [comment]
Thanks for your feedback.

A version suitable for Ubuntu 22.04 has been uploaded to the release page: https://github.com/degaart/firefox-user-installer/releases/tag/v0.1.0
